version: '2'
services:
  atlas:
    restart: always
    build: .
    ports:
      - '${ATLAS_PORT:-5000}:5000'
    environment:
      - ATLAS_PORT=5000
    volumes:
      - .env:/usr/src/app/dist/.env
      - ./cache:/usr/src/app/dist/cache
